---
galaxy_info:
  role_name: "common"
  author: "Red Hat"
  description: "Sets up a generic MCP build environment and installs MCP servers from multiple sources (Go, npm, PyPI)"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.16.0"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - mcp
    - github
    - git
    - image
    - builder
    - ee

collections:
  - ansible.mcp
